name: Generate XML Sitemap

on:
  push:
    branches:
      - main
  workflow_dispatch: # Memungkinkan menjalankan manual dari tab Actions

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Generate the sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://streamnow-video.biz.id/
        path-to-root: .
        sitemap-format: xml
        
    - name: Commit and push if changed
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add sitemap.xml
        git diff --quiet && git diff --staged --quiet || (git commit -m "Automated sitemap update" && git push)
